#!/usr/bin/env python
import sys
from string import ljust
import rebase, checkin, init, load, lshistory, sync, reset

commands = [
    init, rebase, checkin, load, lshistory, sync, reset
]

def main():
    args = sys.argv[1:]
    for cmd in commands:
        if args and cmd.__name__ == args[0]:
            return cmd.main(args[1:])
    usage()

def usage():
    print 'usage: gitcc COMMAND [ARGS]\n'
    width = 11
    for cmd in commands:
        print '    %s %s' % (ljust(cmd.__name__, width), cmd.__doc__.split('\n')[0])
    sys.exit(2)

if __name__ == '__main__':
    main()
